
package br.com.stone.autorizador.transaction.wsclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AutorizadorServiceService", targetNamespace = "http://webservice.autorizador.stone.com.br/", wsdlLocation = "http://localhost:8080/servidor-1.0.0-SNAPSHOT/AutorizadorService?wsdl")
public class AutorizadorServiceService
    extends Service
{

    private final static URL AUTORIZADORSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AUTORIZADORSERVICESERVICE_EXCEPTION;
    private final static QName AUTORIZADORSERVICESERVICE_QNAME = new QName("http://webservice.autorizador.stone.com.br/", "AutorizadorServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/servidor-1.0.0-SNAPSHOT/AutorizadorService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTORIZADORSERVICESERVICE_WSDL_LOCATION = url;
        AUTORIZADORSERVICESERVICE_EXCEPTION = e;
    }

    public AutorizadorServiceService() {
        super(__getWsdlLocation(), AUTORIZADORSERVICESERVICE_QNAME);
    }

    public AutorizadorServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTORIZADORSERVICESERVICE_QNAME, features);
    }

    public AutorizadorServiceService(URL wsdlLocation) {
        super(wsdlLocation, AUTORIZADORSERVICESERVICE_QNAME);
    }

    public AutorizadorServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTORIZADORSERVICESERVICE_QNAME, features);
    }

    public AutorizadorServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AutorizadorServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AutorizadorService
     */
    @WebEndpoint(name = "AutorizadorServicePort")
    public AutorizadorService getAutorizadorServicePort() {
        return super.getPort(new QName("http://webservice.autorizador.stone.com.br/", "AutorizadorServicePort"), AutorizadorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AutorizadorService
     */
    @WebEndpoint(name = "AutorizadorServicePort")
    public AutorizadorService getAutorizadorServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.autorizador.stone.com.br/", "AutorizadorServicePort"), AutorizadorService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTORIZADORSERVICESERVICE_EXCEPTION!= null) {
            throw AUTORIZADORSERVICESERVICE_EXCEPTION;
        }
        return AUTORIZADORSERVICESERVICE_WSDL_LOCATION;
    }

}
