
package br.com.stone.autorizador.wsclient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AutorizadorService", targetNamespace = "http://webservice.autorizador.stone.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AutorizadorService {


    /**
     * 
     * @param arg0
     * @return
     *     returns br.com.stone.autorizador.wsclient.ConsultaTransacoesResposta
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "consultaTransacoes", targetNamespace = "http://webservice.autorizador.stone.com.br/", className = "br.com.stone.autorizador.wsclient.ConsultaTransacoes")
    @ResponseWrapper(localName = "consultaTransacoesResponse", targetNamespace = "http://webservice.autorizador.stone.com.br/", className = "br.com.stone.autorizador.wsclient.ConsultaTransacoesResponse")
    public ConsultaTransacoesResposta consultaTransacoes(
        @WebParam(name = "arg0", targetNamespace = "")
        ConsultaTransacoesSolicitacao arg0);

}
